default_platform :ios

platform :ios do
  desc "Submits a new beta build to TestFlight"
  lane :beta do
    # Run Tests, copying the raw logs to the project folder 
    scan(
    	scheme: "SwiftInfoExample",
    	buildlog_path: "./build/tests_log"
    )
    
    # Archive the app, copying the raw logs to the project folder 
    gym(
     	workspace: "Rapiddo.xcworkspace",
     	scheme: "Marketplace-AppStore",
     	buildlog_path: "./build/build_log"
    )

    # Run SwiftInfo
    sh("../Pods/SwiftInfo/swiftinfo")

    # Commit and push SwiftInfo's result
    # Uncomment me if copying this to a real project
    # sh("git add ../SwiftInfo-output/SwiftInfoOutput.json")
    # sh("git commit -m \"[ci skip] Updating SwiftInfo Output JSON\"")
    # push_to_git_remote
  end
end
